### ISSUE TITLE
Fix Trino pathing support

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-scribe#41]
We see errors such as,

> Trino does not support path expressions on non-variable values

when accessing nested fields in Trino

**Definition of Done**

I need to research, document, and implement Trino pathing operations to the best of my knowledge.

**Comment by alancai98** [comment]
Pasting some Trino path research from the linked PR (https://github.com/partiql/partiql-scribe/pull/68):

### Background on Trino's Support for Paths

Trino has limited support for pathing on structural types such as `ARRAY` and `ROW`s. Alike PartiQL, Trino supports array indexing such as `<some_array>[<int index>]`. Though Trino array indexing is 1-indexed. Scribe already supports transpilation of array indexing:

https://github.com/partiql/partiql-scribe/blob/8bfcb5c85c203d543dfecd14ea9ae2bf25816909/src/test/resources/outputs/trino/basics/paths.sql#L5-L7.

Trino also supports some basic pathing on `ROW`s:

Input table:
```
WITH EXCLUDE_T AS (
	SELECT (
			SELECT (
					SELECT 1 AS field_x,
						'one' AS field_y,
						'1' AS field_z
				) AS a,
				(
					SELECT 2 AS field_x,
						'two' AS field_y,
						'2' AS field_z
				) AS b,
				(
					SELECT 3 AS field_x,
						'three' AS field_y,
						'3' AS field_z
				) AS c
		) AS flds,
		'bar' AS foo
)
```
Non-delimited path query
```
SELECT t.flds.a.field_x
FROM EXCLUDE_T AS t;
```
Outputs:
```
#	field_x
1	1
```

Similarly Trino supports delimited identifier paths:
```
SELECT "t"."flds"."a"."field_x"
FROM EXCLUDE_T AS t;
```

**Comment by alancai98** [comment]
There doesn't seem to be PartiQL's [wildcard and wildcard unpivot support](https://partiql.org/concepts/paths.html#_wildcard_steps) on `ROW` types -- only just the `ROW` field and array indexing.

Interestingly, Trino also has a set of pathing expressions on their JSON type -- https://trino.io/docs/current/functions/json.html#json-path-language.
